name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            autoconf \
            automake \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses-dev \
            cmake \
            libffi-dev \
            libssl-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Download Vosk Model
        run: |
          wget https://alphacephei.com/vosk/models/vosk-model-small-ru-0.22.zip
          unzip vosk-model-small-ru-0.22.zip

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: VoiceSearch-App
          path: bin/*.apk
